### ISSUE TITLE
MySQL python plugin segfaults upon successful connection to the MySQL server

### ISSUE THREAD

**Issue by cobrafast** [firehol/netdata#1229]
On my Debian 8 "Jessie" machine, the MySQL python plugin reliably runs into segfault and takes all the other plugins with it, whenever a connection could be made to the server. I could figure out what's causing it to fail so far.

Happens with restricted user as well as with root.

```
mysql-community-server:
  Installed: 5.7.16-1debian8
mysql-community-client:
  Installed: 5.7.16-1debian8
libmysqlclient20:
  Installed: 5.7.16-1debian8
libmysqlclient18:
  Installed: 5.7.5-m15-2debian8
python2.7:
  Installed: 2.7.9-2+deb8u1
python-mysqldb:
  Installed: 1.3.7-1+b1
```
