### ISSUE TITLE
Monitor tomcat without charts,why?

### ISSUE THREAD

**Issue by BecomeBamboo** [firehol/netdata#1254]
**1. ** firstly,amazing software. For project need,I have to monitor apache tomcat ,when I refer to #719 and #852,now the problem is I can see data in web but without any charts,display as follows,I use python modules  @ktsaou @paulfantom ,many thx by heart****

![image](https://cloud.githubusercontent.com/assets/3755288/20345097/905fa05a-ac30-11e6-97ad-a51bcb51b05a.png)

**2. now my python is 2.7.12,as follows:**

![image](https://cloud.githubusercontent.com/assets/3755288/20345137/b4d39a2c-ac30-11e6-93ed-2c95a16221fc.png)

**tomcat version: 7.0.64**

![image](https://cloud.githubusercontent.com/assets/3755288/20345465/420f0880-ac32-11e6-9d99-50643222d44e.png)

**centos version: centos 6.8 x64**

![image](https://cloud.githubusercontent.com/assets/3755288/20345508/6b3c8b60-ac32-11e6-957e-487f0bce1a3d.png)

**3. tomcat.conf as follows:I have noticed Yaml format.**

```
localhost:
  name: 'local'
  url: 'http://localhost:8080/manager/status?XML=true'
  user: 'tomcat'
  pass: '12345'

localipv4:
  name: 'local'
  url: 'http://127.0.0.1:8080/manager/status?XML=true'

localipv6:
  name: 'local'
  url: 'http://[::1]:8080/manager/status?XML=true'
```

**4. here is the error.log**

![image](https://cloud.githubusercontent.com/assets/3755288/20345307/8a8f640c-ac31-11e6-9b44-e8f0939d4507.png)

![image](https://cloud.githubusercontent.com/assets/3755288/20345321/a1343ee4-ac31-11e6-8a51-307bf90f52cc.png)

**so,what's the problem?I'm in urgent,and forgive my poor english,many thx.**

**Comment by ktsaou** [comment]
Well, it says "Error 401: Unauthorized". This is returned by tomcat.

Could you please run, by hand:

```sh
/usr/libexec/netdata/plugins.d/python.d.plugin debug 1 tomcat
```

**Comment by BecomeBamboo** [comment]
great thx,I have tried ,as follows,It seems error 401 is a big problem,my project use apache tomcat port 8080,so shuould I use another port to monitor the tomcat?

![image](https://cloud.githubusercontent.com/assets/3755288/20372369/b5ea7316-aca5-11e6-80c2-8b607e8d20d4.png)

**Comment by BecomeBamboo** [comment]
now it works,many thx, I have modified tomcat-user.xml,like this:
```
<role rolename="tomcat"/>
  <role rolename="role1"/>
  <role rolename="admin-gui"/>
  <role rolename="admin-script"/>
  <role rolename="manager-gui"/>
  <role rolename="manager-script"/>
  <role rolename="manager-jmx"/>
  <role rolename="manager-status"/>
  <user username="tomcat" password="tomcat" roles="tomcat"/>
  <user username="both" password="tomcat" roles="tomcat,role1"/>
  <user username="role1" password="tomcat" roles="role1"/>
  <user username="prs3000" password="prs3000" roles="tomcat,role1,manager-gui,manager-script,manager-jmx,manager-status,admin-script,admin-gui"/>
```

and modified tomcat.conf:

```
localhost:
  name: 'local'
  url: 'http://localhost:8080/manager/status?XML=true'
  user: 'prs3000'
  pass: 'prs3000'
```

now it works,as follows:
![image](https://cloud.githubusercontent.com/assets/3755288/20454106/78a1a150-ae71-11e6-83be-126261f045f9.png)

now the last question is ,can I set up limit val of JVM memory so I can received alrm message?many thx,I think maybe health.d plugin could work,really?
