### ISSUE TITLE
dns response time plugin question

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1393]
Its not server related thats why i am asking. If some of you guys are interested in it i can make a pull req or share.

How it works.
Configuration file (all of the following nameservers in my example are public):
```yaml
default:
 aggregate: 'no'
 response_timeout: '3'
 dns_servers: '209.244.0.3 64.6.64.6 8.8.8.8 84.200.69.80'
 domains 'distrowatch.com linuxmint.com linux.com rsyslog.com liblognorm.com archlinux.org cisco.com debian.org kernel.org gns3.com opera.com github.com youtube.com amazon.co.uk kde.org netdata.firehol.org ubuntu.com redhat.com opensuse.org wireshark.org vmware.com microsoft.com elastic.co'
```

**response_timeout:** time to wait for response from server. If _dns request query time > response_timeout_  query time is set to negative value.
**dns_servers:** random domain name from the list chosen for each new request for each server
**aggregate:** aggregate all servers in one chart or not

**aggregate: yes**
![aggr](https://cloud.githubusercontent.com/assets/22274335/21287608/c0176158-c4b2-11e6-9565-88a7e9d7fb89.png)

**aggregate: no**
![no_aggr](https://cloud.githubusercontent.com/assets/22274335/21287614/d576c214-c4b2-11e6-95f2-82901459a705.png)
