### ISSUE TITLE
Prometheus Support

### ISSUE THREAD

**Issue by ldelossa** [firehol/netdata#1497]
Hey guys,

I recently started using prometheus and I enjoy the simplicity. I want to begin to understand what it would take to implement prometheus support within Netdata. I think this is a great idea because it allows the distributed fashion of netdata to exist along with having persistence at prometheus. Centralized graphing (not monitoring) can now happen with grafana. Netdata is a treasure trove of metrics already - making this a worth wild project. 

Prometheus expects a rest end point to exist which publishes a metric, labels, and values. It will poll this endpoint at a desired time frame and ingest the metrics during that poll. 

To get the ball rolling, how are you currently serving http in Netdata? Is this an embedded sockets server in C ?

**Comment by ktsaou** [comment]
Hi, thanks! nice you like netdata!

So, you want prometheus to pull data from netdata? netdata has an API. Check: https://github.com/firehol/netdata/wiki/REST-API-v1

But, I also see that data can be pushed to prometheus: https://github.com/prometheus/pushgateway
This one seems very simple to be supported in netdata. Check: https://github.com/firehol/netdata/wiki/netdata-backends#adding-more-backends

**Comment by ktsaou** [comment]
> Is this an embedded sockets server in C ?

yeap!

**Comment by brian-brazil** [comment]
Prometheus developer here. If you want to integrate the best way would be to expose our text exposition format over HTTP. The spec is at https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details. Collectd and telegraf do this for example.

**Comment by ktsaou** [comment]
@brian-brazil thanks for joining this discussion.

So, for prometheus, is it better to send:

```
prefix.host.chart{metric="dimension_name"} value timestamp
```

or

```
prefix.host.chart.dimension value timestamp
```

where:

- `prefix` is user controlled (by default `netdata`).
- `host` is the hostname of the machine (also user defined)
- `chart` is the chart id (netdata also maintains names for charts)
- `dimension` is the dimension id of the chart (netdata also maintains names for dimensions)

all the above are alphanumeric, possibly with ` . `, ` - ` and ` _ `.

Also, does prometheus respond something back?

**Comment by ktsaou** [comment]
@brian-brazil another question:

I see an HTTP header is needed. So, netdata will send an HTTP header on connect, and then stream metrics forever. The HTTP header has to be present only on socket connection. Is that right?

Which URL and HTTP method should be used?

**Comment by ktsaou** [comment]
I pushed some code to implement this. However, there is no HTTP header yet, so it won't work. Once we add the HTTP header we can test it.

**Comment by ldelossa** [comment]
@ktsaou

Are you leaning towards implementing a endpoint on the netdata API which will export these metrics? 

I see exporters written as middleware for Prometheus but I believe integrating it into the native API is nicer to maintain its distributored nature

**Comment by brian-brazil** [comment]
>So, for prometheus, is it better to send:

`prefix.chartname{dimensionname="dimensionvalue"} value`

Prefix should be hardcoded. As you have a per-host daemon, Prometheus would optimally be hitting each of these so it'll be applying the `instance` label on its end.

Generally avoid timestamps, the way it's meant to work is that you'll fetch data when the request comes in.

> Also, does prometheus respond something back?
> I see an HTTP header is needed. So, netdata will send an HTTP header on connect, and then stream metrics forever. The HTTP header has to be present only on socket connection. Is that right?

Prometheus is a pull based system. You'll receive a GET, usually to `/metrics`. Setting the appropriate content-type header is encouraged in your response.

**Comment by ktsaou** [comment]
Oh... I see. You want it the other way around. Prometheus to pull the data from netdata.

> you'll fetch data when the request comes in

It is a bit more complex than that: netdata has an internal round-robin database with 1k-5k metrics per server, all updated every second. With the rate we add metrics, netdata will reach 10k metrics per server in a few months.

If prometheus hits netdata servers once every 10 seconds, it will get back the value of the latest 1 second out of 10. Prometheus will miss 9 seconds of data.

netdata can reduce the data. So, if you hit each netdata once every 10 seconds, you can ask netdata to give you the average of the last 10 seconds. Actually, you can give to netdata the starting and the ending timestamps and the grouping method (average, min, max, sum, etc).

netdata has already an API for all that. The netdata dashboards use it (this is how zooming out netdata charts is so fast). It is plain JSON and is documented here: https://github.com/firehol/netdata/wiki/REST-API-v1

So, can prometheus adapt to the netdata API?

If this too complex for prometheus, I would suggest to do it the other way around: netdata to push data to prometheus. The backend module in netdata already knows how to handle this properly, without stressing each server and without losing data if the backend is down for a short period of time. It also provides alarms in case the backend server loses data.

**Comment by brian-brazil** [comment]
> netdata can reduce the data. So, if you hit each netdata once every 10 seconds, you can ask netdata to give you the average of the last 10 seconds. Actually, you can give to netdata the starting and the ending timestamps and the grouping method (average, min, max, sum, etc).

We'd prefer to get the raw data, and handle the processing on our end. Do you have the notion of counters and gauges?

> If this too complex for prometheus, I would suggest to do it the other way around: netdata to push data to prometheus.

Prometheus can't be operated in that fashion.

**Comment by ktsaou** [comment]
> We'd prefer to get the raw data, and handle the processing on our end. Do you have the notion of counters and gauges?

Yes of course, but netdata interpolates everything to provide a fixed step time-series database, ready to be used in charts.

netdata maintains also the last collected value, as collected, and the exact time in microseconds it was collected. I guess this is what interests you. Unfortunately, there is no API to get these...

So, what you need, is an API call to get all the metrics, as collected.

Let me check how hard that can be...

**Comment by ktsaou** [comment]
Almost done.

The URL will be:

`http://netdata.ip:19999/api/v1/allmetrics?format=prometheus` with a `GET`.

The output header will be:

```
HTTP/1.1 200 OK
Connection: keep-alive
Server: NetData Embedded HTTP Server
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: text/plain; charset=utf-8
Date: Tue, 03 Jan 2017 18:35:58 GMT
Cache-Control: no-cache
Expires: Tue, 03 Jan 2017 18:35:59 GMT
Content-Encoding: gzip
Transfer-Encoding: chunked
```

`keep-alive` and `gzip` are controlled by the caller.

The text output will be something like:

```sh
# HELP net_packets.enp4s0.received packets/s
# TYPE net_packets.enp4s0.received counter
net_packets.enp4s0.received 9768385.0000000 1483468558004
# HELP net_packets.enp4s0.sent packets/s
# TYPE net_packets.enp4s0.sent counter
net_packets.enp4s0.sent 7795059.0000000 1483468558004
# HELP net_packets.enp4s0.multicast packets/s
# TYPE net_packets.enp4s0.multicast counter
net_packets.enp4s0.multicast 1224642.0000000 1483468558004

# HELP net.enp4s0.received kilobits/s
# TYPE net.enp4s0.received counter
net.enp4s0.received 80013394.5546875 1483468558004
# HELP net.enp4s0.sent kilobits/s
# TYPE net.enp4s0.sent counter
net.enp4s0.sent 9992442.7734375 1483468558004
```

I haven't used the format you suggested, because I couldn't figure out what to put on the 2 values requested on each line. If you want it in a different way, please let know.

The `HELP` line states the netdata `units`. For `counter` metrics that rate is invalid (since you get raw data), but the rest is ok (in the above example, the values given are `kilobits` since boot, not `kilobits/s`). If this is misleading I can remove the entire line.

Any comments?

**Comment by brian-brazil** [comment]
> Content-Type: text/plain; charset=utf-8

This should be `text/plain; version=0.0.4`


```
# HELP net_packets.enp4s0.received packets/s
# TYPE net_packets.enp4s0.received counter
net_packets.enp4s0.received 9768385.0000000 1483468558004
```

That's a gauge, not a counter. Periods are not permitted in metric names, you should use underscores instead. The host should also be in a label called "instance".

> # HELP net.enp4s0.received kilobits/s

Can you normalise to bytes?

**Comment by ktsaou** [comment]
ok, you didn't read my comment about the units. Never mind I removed the units.

here is the body:

```
# TYPE net_packets.enp4s0.received counter
net_packets_enp4s0.received{instance="costa_pc"} 10046601 1483475542004
# TYPE net_packets.enp4s0.sent counter
net_packets_enp4s0.sent{instance="costa_pc"} 7999326 1483475542004
# TYPE net_packets.enp4s0.multicast counter
net_packets_enp4s0.multicast{instance="costa_pc"} 1245691 1483475542004

# TYPE net.enp4s0.received counter
net_enp4s0.received{instance="costa_pc"} 10548852286 1483475542004
# TYPE net.enp4s0.sent counter
net_enp4s0.sent{instance="costa_pc"} 1303642094 1483475542004

# TYPE system.load.load1 gauge
system_load.load1{instance="costa_pc"} 3250 1483475540000
# TYPE system.load.load5 gauge
system_load.load5{instance="costa_pc"} 2690 1483475540000
# TYPE system.load.load15 gauge
system_load.load15{instance="costa_pc"} 2250 1483475540000
```

Now the data are raw (as collected, whatever collected). I removed the `HELP` line because netdata does not have any means to know what it is (it knows how to evaluate it to something else - but it does not have a test representation of what it is).

Here is the HTTP response header:

```
HTTP/1.1 200 OK
Connection: keep-alive
Server: NetData Embedded HTTP Server
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: text/plain; version=0.0.4
Date: Tue, 03 Jan 2017 20:38:26 GMT
Cache-Control: no-cache
Expires: Tue, 03 Jan 2017 20:38:27 GMT
Content-Encoding: gzip
Transfer-Encoding: chunked
```

Is it ok now?

**Comment by ktsaou** [comment]
wait... a dot is left in the dimension names...

**Comment by ktsaou** [comment]
ok, updated it.
Please review it.

**Comment by brian-brazil** [comment]
That looks mostly okay. enp4s0 should be a label I think.

**Comment by ktsaou** [comment]
> enp4s0 should be a label I think.

hm... netdata maintains a `context` for each metric and a `family`. Normally `context + family = chart id` (i.e. context `net.bandwidth` + family `enp4s0` is the final chart). But, I can't commit that there will be no overlaps.

Do you want to try it?

**Comment by brian-brazil** [comment]
If you've a full metrics output I can look at we can see what the tradeoff is, as I suspect many of the families wouldn't be labels.

**Comment by ktsaou** [comment]
ok.

- this is the original: http://pastebin.com/ThJWU3uv

- this is with families: http://pastebin.com/9geNGH8m

keep in mind that netdata maintains these for each chart:

1. `type` is the first level of the chart menu
2. `family` is the second level of the chart menu
3. `context` is the prototype of the chart (i.e. all mysql bandwidth charts, have `context = mysql.net`)
4. `type.id` uniquely identifies the chart - there are variations on how this is formed. In a few cases it is `type_family.id`, on others it is `type_id.family` (yes, I know it is stupid - this is why we need to normalize them #807 )
5. `type.name` is an friendly alias for the chart (in most of the cases this is `chart.id` too)
6. `units` is the units of the chart
7. `title` is the title of the chart

Then, for dimensions:

1. `id` that uniquely identifies the dimension within the chart
2. `name` an alias for `id`, that can also be used to identify the dimension (an example where this is used is the interrupts charts - the `id` is the number interrupt number, while `name` is composed by the devices using this interrupt).

**Comment by ktsaou** [comment]
I have not committed the new code. Please let me know which one you prefer to merge it.

**Comment by ktsaou** [comment]
I had to merge it.
Let me know and I'll update it to your preference.

**Comment by ktsaou** [comment]
ok. thanks!
This is already merged.
Can anyone test it please?

**Comment by ldelossa** [comment]
This is great. The amount of data exposed is exciting.

I can can definitely help test within the next few days.

**Comment by brian-brazil** [comment]
Because this is coming from a concentrator that's setting an instance label, make sure to set `honor_labels: true`

**Comment by ldelossa** [comment]
I can definitely give a hand with that, and a quick 'How to' tutorial on
getting it all setup. Just give me a few days the end of this week is
proving to be a little hectic. I'm eager to try this out.

It looks like most your metrics (from the examples) are going to be gauges
and not incrementing counters ? If so that just means we have to graph
these queries a little differently then the current Node Exporter that
prometheus officially supports.

**Comment by ktsaou** [comment]
nice!

> It looks like most your metrics (from the examples) are going to be gauges
> and not incrementing counters

no, this is not the case. netdata exposes the metrics to prometheus the same way it collects them. `absolute` netdata metrics are `gauge` in prometheus, `incremental` netdata metrics are `counter` in prometheus.

**Comment by ldelossa** [comment]
Okay awesome.

**Comment by ldelossa** [comment]
Finally had some time to start testing. I have a test box up and everything hooked up. Give me a day or so to graph some stuff and come up with a small tutorial.

**Comment by ldelossa** [comment]
https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus

**Comment by brian-brazil** [comment]
You'll need to use `params` to pass the format parameter.

**Comment by ldelossa** [comment]
Oh really ? It seems to be working like this but let me adjust. Not at he computer at this moment.

**Comment by brian-brazil** [comment]
If it does there's a bug on the netdata http requesting parsing side, as it's getting `/api/v1/allmetrics%3Fformat=prometheus` as the path.

**Comment by ktsaou** [comment]
@ldelossa thank you for the wiki page! You may need to link it to the backends page.

Regarding the URL parsing, could you please check netdata's access.log? I think the question mark that separates the query string from the path should be escaped. But let's check what netdata receives...

**Comment by ldelossa** [comment]
@brian-brazil @ktsaou 

Sorry about the huge delay there, had some stuff to take care of. I'm actually returning to this now and it's working rather well for me. I'm using it with consul at this point - this is the prometheus.yml file that works for me. 

```
# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: netdata
    metrics_path: "/api/v1/allmetrics?format=prometheus"

    consul_sd_configs:
    - server: 'moosive-consul-01:8500'
      token: "B019F0AC-2754-4DDE-9DB4-AD29FF859B46"
      #datacenter: "GCE-Vimeo-Player"
      services: ['netdata']

    relabel_configs:
    - source_labels: [__meta_consul_node]
      regex: (.+)
      target_label: instance
      replacement: '${1}'
```

I do not see any issues as of right now. Brian, where is the param directive you're saying would cause an issue?

**Comment by brian-brazil** [comment]
The metrics_path should be just `/api/v1/allmetrics` and the format passed as a param.

**Comment by ldelossa** [comment]
so attempting this:

```
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: netdata
    metrics_path: "/api/v1/allmetrics"
    params: "format=prometheus"

    consul_sd_configs:
    - server: 'moosive-consul-01:8500'
      token: 
      services: ['netdata']

    relabel_configs:
    - source_labels: [__meta_consul_node]
      regex: (.+)
      target_label: instance
      replacement: '${1}'
```

I get an unmarshall error. 

```
Mar 12 15:50:38 moosive-stats-01 prometheus[1544]: time="2017-03-12T15:50:38Z" level=error msg="Error loading config: couldn't load configuration (-config.file=/opt/prometheus/prometheus.yml): yaml: unmarshal errors:\n  line 31: cannot unmarshal !!str `format=...` into url.Values" source="main.go:150"
```
