### ISSUE TITLE
Question : Multiple instances of redis

### ISSUE THREAD

**Issue by divgwd** [firehol/netdata#1946]
Hi,
I wanted to know if it is possible to enable netdata to monitor many instances of redis on the same server ??
if there is ,can you tell me how to do it??
Also, Thank you for this wonderful monitoring tool : ).
Thanks in advance :)

**Comment by l2isbad** [comment]
Hi @divgwd 

```yaml
redis_1:
  host     : '1.2.3.4'
  port     : 6379

redis_2:
  host     : '1.2.3.5'
  port     : 6378

redis_3:
  host     : '1.2.3.6'
  port     : 6377
```
