### ISSUE TITLE
Running netdata in docker based alpine 

### ISSUE THREAD

**Issue by t3chn0m4g3** [firehol/netdata#2197]
I created an alpine based docker image...
```
FROM alpine
MAINTAINER MO

# Install packages
RUN apk -U upgrade && \
    apk add autoconf \
            automake \
            bash \
            build-base \
            curl \
            gawk \
            git \
            jq \
            libuuid \
            linux-headers \
            musl-dev \
            util-linux-dev \
            libmnl-dev \
            zlib-dev && \

# Install netdata
    cd /root && \
    git clone https://github.com/firehol/netdata -b v1.6.0 && \
    cd netdata && \
    ./netdata-installer.sh --dont-wait --dont-start-it && \
    cd .. && \

# Clean up
    apk del git && \
    rm -rf /root/* && \
    rm -rf /var/cache/apk/*

# Start netdata 
WORKDIR /
CMD ["/usr/sbin/netdata","-D","-s","/host","-i","127.0.0.1","-p","64301"]
```

and start it with ...
```
# Netdata service
  netdata:
    container_name: netdata
    restart: always
    network_mode: "host"
    cap_add:
     - SYS_PTRACE
    security_opt:
     - apparmor=unconfined
    image: "dtagdevsec/netdata:1706"
    volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /var/run/docker.sock:/var/run/docker.sock
```

While everything works just fine, for some unknown reason netdata is unable to resolve docker container names on the host (netdata user is also part of the docker group).

Using a debian / ubuntu based docker image works just fine, so I am guessing it might have something to do with `musl` or a dependency that I might have missed.

Here are the logs ...
[log.txt](https://github.com/firehol/netdata/files/1008197/log.txt)
