### ISSUE TITLE
HAProxy plugin stats multi process - Improvement

### ISSUE THREAD

**Issue by dseira** [firehol/netdata#2323]
Hi,

It would be really useful to be able to graph the haproxy stats when it is configured as multi-process like this:

```
global
    nbproc 4
    stats socket /run/haproxy/admin1.sock mode 660 level admin user root group haproxy process 1
    stats socket /run/haproxy/admin2.sock mode 660 level admin user root group haproxy process 2
    stats socket /run/haproxy/admin3.sock mode 660 level admin user root group haproxy process 3
    stats socket /run/haproxy/admin4.sock mode 660 level admin user root group haproxy process 4
```

The only difference is that you have more than one socket to listen to.

I don't know if it is better to graph every socket separately or join them together in the same graph (could be both as a kind of summary).

**Comment by ktsaou** [comment]
I understand netdata can already provide stats for each socket if you configure it to. You can add many such sections in the config to get multiple sections, one for each socket : https://github.com/firehol/netdata/blob/fcda480adff2702d8f71e652598998e94133d052/conf.d/python.d/haproxy.conf#L77-L78

Have you tried that?

Joining all together, is more of a visualization problem. There are many similar requests already for providing a unified chart for clusters.

**Comment by dseira** [comment]
Yes, you're right. Every graph individually works adding subsections:

```
haproxy1:
    socket: /run/haproxy/admin1.sock
haproxy2:
    socket: /run/haproxy/admin2.sock
haproxy3:
    socket: /run/haproxy/admin3.sock
haproxy4:
    socket: /run/haproxy/admin4.sock
```

Thanks.
