### ISSUE TITLE
config file format

### ISSUE THREAD

**Issue by paulczar** [firehol/netdata#2487]
I made the hasty assumption that the config file format for netdata was a python style ini file however after working more with netdata this seems to have been a horrible mistake and that while it sort of looks like an ini file ... its not really.

Is there any chance of updating the config libraries to support a more standard format so that tooling in config management like ansible's [ini_file](http://docs.ansible.com/ansible/latest/ini_file_module.html) module works with it for making config changes?

In the end I had to write the following jinja2 template to take a dictionary and turn it into a config that netdata would accept:

```
netdata:
  config:
    global:
      run_as_user: netdata
      web_files_owner: root
      web_files_group: netdata
```

```
{% for section in netdata.config %}
[{{ section }}]
{% for item in netdata.config[section] %}
{{ "\t" }}{{ item | regex_replace('_',' ') }} = {{ netdata.config[section][item] }}
{% endfor %}
{% endfor %}
```
