### ISSUE TITLE
MySQL plugin doesn´t work

### ISSUE THREAD

**Issue by benhartwich** [firehol/netdata#2492]
Hi,

great software! But the python plugin for implementing mysql analytics doesn´t work. 

At the error log of netdata is:
2017-07-21 11:29:23: python.d ERROR: mysql: cannot parse configuration file '/etc/netdata/python.d/mysql.conf': argument of type 'NoneType' is not iterable

At /etc/netdata/python.d/mysql.conf I´ve commented everything out except:
```
tcp_netdata:
  name     : 'local'
  user     : 'netdata'
  pass     : 'test123'
  host     : '127.0.0.1'
  port     : '3306'
```

Has anyone a further debugging hint?

Regards,

**Comment by l2isbad** [comment]
hi @benhartwich 

```yaml
tcp_netdata:
  name : 'local'
  user : 'netdata'
  pass : 'test123'
  host : '127.0.0.1'
  port : '3306'
```
