### ISSUE TITLE
Config settings ignored

### ISSUE THREAD

**Issue by Synchro** [firehol/netdata#2551]
I'm finding the docs very confusing - the formats used seem to vary a lot and don't agree, for example I'm looking at [web_log](https://github.com/firehol/netdata/tree/master/python.d#web_log), and I need to set the path to the log file I want it to read.

It describes its config like this:

```yaml
nginx_log:
  name  : 'nginx_log'
  path  : '/var/log/nginx/access.log'

apache_log:
  name  : 'apache_log'
  path  : '/var/log/apache/other_vhosts_access.log'
  categories:
      cacti : 'cacti.*'
      observium : 'observium'
```

Looking at [the code](https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L289), it gets this value from a `path` property passed from config (which uses an ini style rather than this yaml, which I gather from the docs that I'm not supposed to touch).

[The web_log config file](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L62) also describes this `path` property. I don't understand why these config settings appear in three places.

So in my netdata.conf file I set this option:

```
[plugin:web_log]
path = /var/log/myaccess.log
```

But nothing shows up in the UI. If I ask it to show my config, it says:

```
# section 'plugin:web_log' is not used.
[plugin:web_log]
	path = /var/log/myaccess.log
```

I tried calling it `[plugin:apache_log]`, but that acted the same. Adding a `name = local` to try to match the other configs didn't help either.

If I test-run the plugin (`/usr/libexec/netdata/plugins.d/python.d.plugin 1 debug web_log`) it fails because it's not picked up my config.

How am I supposed to do this? Isn't this all supposed to be driven from the netdata.conf file?
