### ISSUE TITLE
Providing auxiliary data for charts

### ISSUE THREAD

**Issue by magao** [firehol/netdata#2776]
I have a use case that I think currently isn't handled by NetData (if it is, please tell me how to do it).

I am creating a chart of internet bandwidth usage by client (by parsing `/proc/net/ip_conntrack` from my router). Currently I'm using statsd and creating 254 series on the chart - one per IP in my /24 subnet (eventually I aim to convert this into a plugin and only create series where there are actually connections).

What I want to do is when a series is highlighted, display the IP address (series name) and arbitrary text - a description, DNS name (if known), etc for the series.

I've created a custom dashboard with this chart and written the code to be able to hook in and display the IP address (get the name using `highlightSeriesOpts` and wrap `highlightCallback`/`unhighlightCallback` to set/unset `dygraph_instance.canvas_.title`). So far so good - I get the IP address as a tooltip.

However, there doesn't appear to be a way to get the descriptive information to display. I've implemented a workaround where I actually write a `.csv` file to the NetData web directory, then retrieve that like:

```
$.ajax({
    url: '/clients.csv',
}
```

Obviously this is an ugly hack. What I'd like to be able to do once I've converted it into a plugin is hook into the REST API and have the plugin specify auxiliary data that I can use. I'm thinking that having a new parameter for `/api/v1/data` specifying the type of data would work e.g.:

```
http://127.0.0.1:19999/api/v1/data?chart=router.client&type=hostname

/data:
  get:
    parameters:
      - name: type
        in: query
        description: 'The type of data to be returned.'
        required: true
        type: string
        default: chart
        allowEmptyValue: false
```

The default `type=chart` would return the existing data used to populate a chart. If any other type is specified, the API parameters would be passed to the plugin that generated the chart, and it would return the auxiliary data (if any) formatted appropriately (with maybe the option of returning JSON and letting the API engine convert it to other formats, although I don't know if that's possible for all formats).
