### ISSUE TITLE
Custom Web Log

### ISSUE THREAD

**Issue by vaheminasyan** [firehol/netdata#3139]
Hi. I have a web_log configuration like this:

```
api_cached:
  all_time : 'no'
  name: 'api_cached'
  path: '/var/log/nginx/api.access.log'
  custom_log_format:
    pattern: '(?P<hostname>[.a-z0-9-]+)::(?P<code>3\d{2})::(?P<bytes_sent>\d+)::(?P<request_time>[0-9.]+)::(?P<address>[0-9a-f.:]+|-)::(?P<url>.*?)::.+?(?P<method>GET|POST|HEAD|PUT|DELETE|OPTIONS|CONNECT)::.+?(?P<http_country_code>[A-Z]{2}|-)::.* '
```

```
api_uncached:
  all_time : 'no'
  name: 'api_uncached'
  path: '/var/log/nginx/api.access.log'
  custom_log_format:
    pattern: '(?P<hostname>[.a-z0-9-]+)::(?P<code>2\d{2})::(?P<bytes_sent>\d+)::(?P<request_time>[0-9.]+)::(?P<address>[0-9a-f.:]+|-)::(?P<url>.*?)::.+?(?P<method>GET|POST|HEAD|PUT|DELETE|OPTIONS|CONNECT)::.+?(?P<http_country_code>[A-Z]{2}|-)::.* '

```

Both of them sometimes fail and sometimes work when restarting netdata

**Comment by l2isbad** [comment]
Well, i believe the problem is hard coded (?P\<code\>**3**\d{2}).
I see
https://github.com/firehol/netdata/blob/master/python.d/web_log.chart.py#L586-L588

(if regex fails to parse `last_line` `check()` fails too)

`last_line` is literally last line from the log file. \<code\> can be any - `200`, `400`, etc.

You can use [filter](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L74-L75) feature

like

```yaml
api_cached:
  all_time : 'no'
  name: 'api_cached'
  path: '/var/log/nginx/api.access.log'
  filter:
    include: '[.a-z0-9-]+::2\d{2}::'
  custom_log_format:
    pattern: '(?P<hostname>[.a-z0-9-]+)::(?P<code>3\d{2})::(?P<bytes_sent>\d+)::(?P<request_time>[0-9.]+)::(?P<address>[0-9a-f.:]+|-)::(?P<url>.*?)::.+?(?P<method>GET|POST|HEAD|PUT|DELETE|OPTIONS|CONNECT)::.+?(?P<http_country_code>[A-Z]{2}|-)::'


api_uncached:
  all_time : 'no'
  name: 'api_uncached'
  path: '/var/log/nginx/api.access.log'
  filter:
    include: '[.a-z0-9-]+::3\d{2}::'
  custom_log_format:
    pattern: '(?P<hostname>[.a-z0-9-]+)::(?P<code>2\d{2})::(?P<bytes_sent>\d+)::(?P<request_time>[0-9.]+)::(?P<address>[0-9a-f.:]+|-)::(?P<url>.*?)::.+?(?P<method>GET|POST|HEAD|PUT|DELETE|OPTIONS|CONNECT)::.+?(?P<http_country_code>[A-Z]{2}|-):: '

```
