### ISSUE TITLE
ISC dhcpd: How to monitor IPv6

### ISSUE THREAD

**Issue by agross** [firehol/netdata#3174]
Hi,

I installed ISC dhcpd for IPv4 and IPv6 (stateful DHCPv6). I added this to my config:

```yaml
dhcpd:
  name: IPv4
  update_every: 1
  priority: 60000
  retries: 60
  autodetection_retry: 0
  leases_path: '/var/lib/dhcpd/dhcpd.leases'
  pools:
    172.16.0.0/24: '172.16.0.0/24'

dhcpd6:
  name: IPv6
  update_every: 1
  priority: 60000
  retries: 60
  autodetection_retry: 0
  leases_path: '/var/lib/dhcpd/dhcpd6.leases'
  pools:
    2001:470:1f0b:c9a::/64: '2001:470:1f0b:c9a::/64'
```

Questions:

1. IPv6 stats do not show up, graphs do (all zeros)
1. Ad 1: How do I need to configure the IPv6 pool(s). Perhaps it's best to add a sample to the default config
1. IPv4 stats are displayed in the IPv6 charts as well, but with `-` values

You can [check the current setup here](https://router.netdata.home.therightstuff.de/#menu_isc_dhcpd_IPv4_submenu_utilization;theme=slate;help=true).
