### ISSUE TITLE
Monitoring DHCP Server

### ISSUE THREAD

**Issue by hornjt75862** [firehol/netdata#3189]
I have a RaspberryPi, running Pi-Hole which I am using for DNS and DHCP. I am trying to setup Netdata to monitor the DHCP Server. I've configured the python.d/isc-dhcpd.conf  file and when I try to verify the isc-dhcpd it does get some errors, but then it starts returning data (doesn't look like dhcp data though.

In the error.log file I am getting:
2017-12-28 11:36:18: python.d ERROR: isc_dhcpd: job_name: 'python-ipaddress' module is needed
2017-12-28 11:36:18: python.d ERROR: isc_dhcpd: job_name: check() => [FAILED]

not sure how to "install" python-ipaddress module.

In the configuration file: python.d/isc-dhcpd.conf, I have:
leases_path: '/etc/pihole/dhcp.leases'                    # the path to dhcpd.leases file
     pools: '192.168.254.0/24'

and have checked to verify netdata can read get to the file.

**Comment by l2isbad** [comment]
Depends on distro
`debian` like:
sudo apt-get install python-ipaddress

`centos` like:
yum install python-ipaddress

**Comment by ktsaou** [comment]
@l2isbad can you make a map/table of all the packages required by python.d.plugin modules?

I think we should:

1. add them to required-packages-installer when it is called with `netdata-all` (option `all` to kickstart.sh)
2. add this information to add more charts page
3. add it to the page of each module
4. add it to the config file of each module

So, that people will be able to find it easily.
What do you think?

**Comment by l2isbad** [comment]
I think the current module conf file format is not optimal. We have tons of duplicate information in every conf file (nobody reads it, i am sure).
I think all descriptions/info should be at wiki pages or readme files.
Conf files should consist of several section with variables only. 
Like
```yaml
# GLOBAL
update_every: 1
priority: 60000
retries: 60
autodetection_retry: 0
chart_cleanup: 10

# SERVICE SPECIFIC
# user: 'user'
# pass: 'pass'

# MODULE SPECIFIC
# module has no specific options

# AUTO-DETECTION JOBS
remote1:
  name : 'remote1'
  url  : 'url1'

remote2:
  name : 'remote2'
  url  : 'url2'
```

Actually it is a good topic for discussion.
