### ISSUE TITLE
Bug about postgres plugin

### ISSUE THREAD

**Issue by BillTian** [firehol/netdata#3301]
When i add multiple database connections in `postgres.conf` with different name, there is ONLY the last ONE postgres chart shown on the dashboard.

for example:

```
tcpipv4:
    name     : 'db1'
    database : 'postgres'
    user     : 'postgres'
    password : 'postgres'
    host     : '127.0.0.1'
    port     : 8543

tcpipv4:
    name     : 'db2'
    database : 'postgres'
    user     : 'postgres'
    password : 'postgres'
    host     : '127.0.0.1'
    port     : 8563
```

only the db2 charts shown on dashboard.

**environment:**
OS: CentOS 6.9
Python: 2.7.14
netdata: 1.9.0

Have i make the mis - configuration ?
Thanks a lot !

**Comment by l2isbad** [comment]
```yaml
tcpipv4_1:
    name     : 'db1'
    database : 'postgres'
    user     : 'postgres'
    password : 'postgres'
    host     : '127.0.0.1'
    port     : 8543

tcpipv4_2:
    name     : 'db2'
    database : 'postgres'
    user     : 'postgres'
    password : 'postgres'
    host     : '127.0.0.1'
    port     : 8563
```

Config is a dict. Keys must be unique.
