### ISSUE TITLE
Elasticsearch read timeout

### ISSUE THREAD

**Issue by hameno** [firehol/netdata#3404]
On our cluster it usually takes about 3-5 seconds to query /_cluster/stats and /_nodes/_local/stats (not sure if we can tune this). This causes the elasticsearch plugin to abort because the read timeout is set to 1 (second?).

Can we adjust this? (We increased update_every to 10)

**Comment by l2isbad** [comment]
hi @hameno 
https://github.com/firehol/netdata/blob/master/python.d/python_modules/bases/FrameworkServices/UrlService.py#L26

```yaml
local
    host: '127.0.0.1'
    port: '9200'
    update_every: 10
    timeout: 8
```
