### ISSUE TITLE
watch many nginx access logs

### ISSUE THREAD

**Issue by xifi-kif** [firehol/netdata#3568]
I'm using netdata on a server which has many access logs and many nginx virtual servers on it.
How can I monitor separately each access log?

in `/etc/netdata/python.d/web_log.conf` can I add this?

```
nginx_log:
  name: 'nginx'
  path: '/var/log/nginx/access1.log'

nginx_log:
  name: 'nginx'
  path: '/var/log/nginx/access2.log'

nginx_log:
  name: 'nginx'
  path: '/var/log/nginx/access3.log'

...

```

And how should it be formatted?

**Comment by l2isbad** [comment]
Change `name1` to whatever you want. The goal is to have different names.

```yaml
nginx_log_name1:
  path: '/var/log/nginx/access1.log'

nginx_log_name2:
  path: '/var/log/nginx/access2.log'

nginx_log_name2:
  path: '/var/log/nginx/access3.log'
```

**Comment by xifi-kif** [comment]
Thanks, actually the "name" has to be different also:

```
nginx_log_1:
  name: 'nginx1'
  path: '/var/log/nginx/access1.log'

nginx_log_2:
  name: 'nginx2'
  path: '/var/log/nginx/access2.log'
```
