### ISSUE TITLE
web_log custom log not picking response time

### ISSUE THREAD

**Issue by vpapas** [firehol/netdata#3823]
Hi,

We have created a custom regex pattern for varnishncsa logs but it is not picking up response time.

The web_log config is the following:

```
#varnishncsa
varnishncsa_log1:
  name: 'varnishncsa'
  path: '/var/log/varnish/varnishncsa.log'
  filter:                             
  include: 'REGEX'            
  custom_log_format:
  pattern: '([F|nonF]5\s+?P<client_address>[\da-f.:]+) (.*) (.*) (\[\d+\/\w+\/\d+\:\d+\:\d+\:\d+\s\+\d+\]) (\"?P<method>\w+) (?P<url>\/.*) (HTTP\/?P<http_version>\d\.\d)(\"\s?P<http_code>[0-9]+|\-) (?P<resp_length>\d+|\-) (.*) (.*) (.*) (.*) (?P<resp_time>\d+|\-) (?P<hitmiss>\w+) (\".*\")'
```

Netdata log says the following:

```
2018-06-14 10:51:37: python.d INFO: web_log: varnishncsa_log1: Collected data: ['request', 'code', 'bytes_sent', 'address']
2018-06-14 10:51:37: python.d INFO: web_log: varnishncsa_log1: check() => [OK]
```
Everything works fine except for response time. 

Can you, please, help?

Thanks.

**Comment by l2isbad** [comment]
Looks like bad `yaml` format
should be

```yaml
#varnishncsa
varnishncsa_log1:
  name: 'varnishncsa'
  path: '/var/log/varnish/varnishncsa.log'
  filter:                             
      include: 'REGEX'            
  custom_log_format:
      pattern: '([F|nonF]5\s+?P<client_address>[\da-f.:]+) (.*) (.*) (\[\d+\/\w+\/\d+\:\d+\:\d+\:\d+\s\+\d+\]) (\"?P<method>\w+) (?P<url>\/.*) (HTTP\/?P<http_version>\d\.\d)(\"\s?P<http_code>[0-9]+|\-) (?P<resp_length>\d+|\-) (.*) (.*) (.*) (.*) (?P<resp_time>\d+|\-) (?P<hitmiss>\w+) (\".*\")'
```
