### ISSUE TITLE
update_every in postgres plugin

### ISSUE THREAD

**Issue by roedie** [firehol/netdata#4089]
Hi,

I'm having an issue with update_every in the postgres plugin. When setting update_every to 10 in the postgres conf I thought it would run every 10 seconds. But it seems to run every 2 seconds. Am I misunderstanding this?

In the netdata global settings I have:
```
history = 1800
update every = 2
```

But in postgres.conf I have:
```
postgres:
  update_every: 10
  name: 'local'
  database: 'postgres'
  host: '127.0.0.1'
  user: 'myleetuser'
  password: 'verycoolpass'
  port: '5432'
```
