### ISSUE TITLE
Using multiple netdata servers with Prometheus

### ISSUE THREAD

**Issue by 74cmonty** [firehol/netdata#4128]
Hi,
in the [wiki](https://github.com/firehol/netdata/wiki/Using-Netdata-with-Prometheus) you describe the usage of netdata with Prometheus.

Question:
Is my understanding correct that I must enter every single netdata server in prometheus.yml
```
static_configs:
      - targets: ['{your.netdata.ip1}:19999 {your.netdata.ip2}:19999']
```
in order to pull data into Prometheus?

What is the correct syntax for multiple targets?

**Comment by paulfantom** [comment]
Here you go:

Prometheus instance: http://demo.cloudalchemy.org:9090/config
Config (using file_sd): https://github.com/cloudalchemy/demo-site/blob/605a0049dee1cef6a34a09d84be423128d9b246b/group_vars/all/vars#L56

Same can be achieved with `static_configs` and listing every server manually.

**Comment by paulfantom** [comment]
Extract from prometheus config:
```yaml
- job_name: netdata
  honor_labels: true
  params:
    format:
    - prometheus
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /api/v1/allmetrics
  scheme: http
  file_sd_configs:
  - files:
    - /etc/prometheus/file_sd/netdata.yml
    refresh_interval: 5m
```

full /etc/prometheus/file_sd/netdata.yml:
```yaml
- labels:
    env: netdata-demo
  targets:
  - london.my-netdata.io
  - atlanta.my-netdata.io
  - sanfrancisco.my-netdata.io
  - toronto.my-netdata.io
  - bangalore.my-netdata.io
  - singapore.my-netdata.io
  - newyork.my-netdata.io
  - frankfurt.my-netdata.io
  - octopuscs.my-netdata.io
  - ventureer.my-netdata.io
  - stackscale.my-netdata.io
```

**Comment by 74cmonty** [comment]
This means you recommend to use **dedicated netdata.yml** and no `static-configs`?

**Comment by paulfantom** [comment]
I recommend to use service discovery with prometheus when it is possible. So yeah, use `netdata.yml`

**Comment by 74cmonty** [comment]
OK.
I tried this config:
_/opt/prometheus/prometheus.yml_ 

```
# my global config
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'netdata-scrape'

    metrics_path: '/api/v1/allmetrics'
    params:
      # format: prometheus | prometheus_all_hosts
      # You can use `prometheus_all_hosts` if you want Prometheus to set the `instance` to your hostnam$
      format: [prometheus]
      #
      # sources: as-collected | raw | average | sum | volume
      # default is: average
      #source: [as-collected]
      #
      # server name for this prometheus - the default is the client IP
      # for netdata to uniquely identify it
      #server: ['prometheus1']
    honor_labels: true
    #scrape_interval: 1m
    #scrape_timeout: 10s
    scheme:http
    file_sd_configs:
      - files:
        - /opt/prometheus/file_sd/netdata.yml
    refresh_interval: 5m

```

_/opt/prometheus/file_sd/netdata.yml_
```
- labels:
    env: netdata-demo
  targets:
  - lvenetdata:19999
  - ld4257:19999
  - ld4464:19999
  - ld4465:19999

```

Starting prometheus fails with this error:
```
level=info ts=2018-09-07T14:07:43.232686095Z caller=main.go:587 msg="Notifier manager stopped"
level=error ts=2018-09-07T14:07:43.232768004Z caller=main.go:596 err="Error loading config couldn't load configuration (--config.file=/opt/prometheus/prometheus.yml): parsing YAML file /opt/prometheus/prometheus.yml: yaml: line 48: could not find expected ':'"

```

Can you please advise?
