### ISSUE TITLE
python plugins: auto-detection

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#602]
@paulfantom I think we have to standardize somehow auto-detection for python plugins.

For example for `mysql` we could try:

1. `/var/run/mysql/mysql.sock`
2. `/var/lib/mysql/mysql.sock`
3. `localhost:3306`

all the above with user `netdata` and user `root`.

Something like that will be needed for squid and possibly other modules that need to detect their application by trying a few alternatives. The whole idea is to stop trying if any of them works, so these are special jobs.

I would prefer all these to be in the configuration file, not the code.

One solution could be to support multiple jobs with the same name, so that only one of them will finally be used. Any other ideas?

**Comment by paulfantom** [comment]
Probably it can be specified as a list of options:
```yaml
local:
  user: 
    - root
    - netdata
  socket: 
    - "/var/run/mysql/mysql.sock"
    - "/var/lib/mysql/mysql.sock"
  host: localhost
```

This way I can check every possible combination and pick the correct one. It shouldn't be too hard to implement.

**Comment by ktsaou** [comment]
We should avoid implementing this in the modules. A lot of work.

What if add a special kind of job: `autodetect`. So only one `autodetect: true` job should be running?

**Comment by paulfantom** [comment]
In modules it is just a couple of nested `for` loops in `check()` function.

I don't understand how `autodetect` should work, could you clarify?

**Comment by ktsaou** [comment]
Oh yes, it is very simple:

1. python.d.plugins loads all modules and all jobs for each module
2. It calls the check() function on each job
3. if it succeeds and the job has `autodetect: true` and it automatically marks as failed (or removes) the other jobs of the same module that have `autodetect: true`.

This way we can have the auto-detection jobs in the configuration file of the module and only one of them (the first that succeeds) will be used.

**Comment by paulfantom** [comment]
What if we have `local` and `remote` instance of the same module, both with `autodetect`? For example application has two default ports, and can be run locally or remotely.

**Comment by ktsaou** [comment]
Then, we could use `autodetect: name`. Jobs with the same `autodetect: name` will be mutually exclusive. This way, each module could support any number autodetections and each autodetection could have any number of mutually exclusive jobs.

**Comment by ktsaou** [comment]
If `autodetect: name` is present, we could also use this `name` for naming the charts...

**Comment by paulfantom** [comment]
Hmmm, like this:
```yaml
local_1:
  port: 8080
  user: bla
  autodetect: local

local_2:
  port: 3124
  user: root
  autodetect: local

remote_1:
  user: chicken
  autodetect: remote

remote_2:
  user: egg
  autodetect: remote
```

This would create 4 jobs, check their configurations, pick correct ones and name jobs with a name from `autodetect`

**Comment by ktsaou** [comment]
yes, exactly. This is nice because the modules need to know nothing about it...

**Comment by paulfantom** [comment]
A little bit counterintuitive configuration, but it is ok, I will try it. This shouldn't be hard to implement.

**Comment by ktsaou** [comment]
instead of the `autodetect` keyword, we could use the keyword `name`, so that the users may also use this feature, for example to connect to a node of a cluster of machines.

**Comment by ktsaou** [comment]
So, jobs with the same `name` are mutually exclusive.

**Comment by paulfantom** [comment]
I will think about keyword, but definitely `name` is at the end of my list. It will be very misleading since currently things like `local_1` from my previous example are used as a job name (and this way a name in dashboard)

**Comment by ktsaou** [comment]
hm... I am not sure it is wrong. Let's see a few examples:

```yaml
autodetect1:
    name: local

autodetect2:
    name: local

node1:
    name: cluster

node2:
    name: cluster
```

The whole idea is that you override the name of the job.

Of course, I am also open to better ideas...

**Comment by paulfantom** [comment]
Currently if you have:
```yaml
remote:
  host: "some_remote_mysql_instance"

local:
  socket: "socket_path"
```

`python.d.plugin` will use everything from this configuration and you will have two clearly named instances in dashboard:
- `MySQL: local`
- `MySQL: remote`

And what if we have it like this:
```yaml
local:
  socket: "path_to_socket"

remote_1:
  name: "remote"
  host: "some_url"

remote_2:
  name: "remote"
  host: "some_other_url"
```

It is a little misleading since we are having same thing in two places of configuration file.
Changing `name` to something like `name_override` will solve this.

**Comment by paulfantom** [comment]
Also it will be simpler to explain in wiki.

**Comment by ktsaou** [comment]
In my version, I would say something like this:

- `job_name`: uniquely identifies a job and is used in error.log for troubleshooting a job.
- `name`: by default is the same with `job_name`. You can set `name` to something else to define mutually exclusive jobs (i.e. jobs that should not be enabled concurrently). The plugin will only allow one job with the given `name`.

This is not so significant. Let's do this with any keyword you like.

**Comment by paulfantom** [comment]
Now that you said it, it makes sense. Tomorrow I will look into code and decide.
This is enough for me today.

**Comment by ktsaou** [comment]
@paulfantom the solution you gave here seems to work. Nice!
However the name reported to netdata should be the `name` fields, not the `job` field.

I tried this config:

```yaml
update_every: 1

mycnf:
  name     : local
  'my.cnf' : '/etc/mysql/my.cnf'

socket1:
  name     : local
  #user     : 'root'
  #password : ''
  socket   : '/var/run/mysqld/mysqld.sock'

socket2:
  name     : local
  #user     : 'root'
  #password : ''
  socket   : '/var/lib/mysqld/mysqld.sock'

tcp:
  name     : local
  #user     : 'root'
  #password : ''
  host     : 'localhost'
  port     : '3306'

socket1_root:
  name     : local
  user     : 'root'
  #password : ''
  socket   : '/var/run/mysqld/mysqld.sock'

socket2_root:
  name     : local
  user     : 'root'
  #password : ''
  socket   : '/var/lib/mysqld/mysqld.sock'

tcp_root:
  name     : local
  user     : 'root'
  #password : ''
  host     : 'localhost'
  port     : '3306'
```

I expected to get charts named `mysql_local`, but I get `mysql_socket1`.
