### ISSUE TITLE
multiple nginx instances

### ISSUE THREAD

**Issue by epema** [firehol/netdata#631]
Hi,

How can I monitor nginx instances besides local? 
http://otherserver1/stub_status
http://otherserver2/stub_status

Thanks.

**Comment by paulfantom** [comment]
I don't think you can do it with `nginx.chart.sh`, but python counterpart can be used to accomplish it.
To enable it in python you need to enable python plugins in `python.d.conf` by changing `enabled = no` to `enabled = yes`. Then you need to create file `nginx.conf` in `python.d` directory with following configuration:

```yaml
otherserver1_custom_name:
  url: "http://otherserver1/stub_status"
otherserver2_custom_name:
  url: "http://otherserver2/stub_status"
```

You can set update frequency by setting `update_every` globally or per server. [More information about python plugins is here.](https://github.com/firehol/netdata/tree/master/python.d)
Configuration file must have valid YAML syntax.
