### ISSUE TITLE
Docker- what files to preserve data?

### ISSUE THREAD

**Issue by kmlucy** [firehol/netdata#884]
I run Netdata in a Docker container. When I remove and recreate the container, I lose the data history. When files should I put in a volume to keep the data history across recreates?

**Comment by ktsaou** [comment]
You need `/var/lib/netdata` and `/var/cache/netdata`.
Keep in mind you should not share these between multiple instances of netdata. If just one netdata is accessing them at any one time, you are ok.

**Comment by kmlucy** [comment]
Great, thanks.

**Comment by bv-ritesh** [comment]
@ktsaou I am facing this issue now. running netdata v1.31.0 inside docker container using docker-compose.
with following compose file.
```

version: '3'
services:
  netdata:
    image: netdata/netdata:v1.31.0
    container_name: netdata
    hostname: netdata_prod
    ports:
      - 19999:19999
      - 19889:19889/udp
    restart: always
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
~                
```

on removing the container i.e 
```
docker-compose stop netdata
docker rm netdata
```

and then again doing
`docker-compose up -d `

all my data is deleted. I have custom statsd data as well in this and everything is lost.
